'use client'

import React, { useState } from 'react'
import { SetlistBuilder } from './SetlistBuilder'

const DOSSIER_SECTIONS = [
  { key: 'perf',      label: 'Performance facts',         on: true  },
  { key: 'position',  label: 'Position breakdown',         on: true  },
  { key: 'versions',  label: 'Versions table (top 25)',    on: true  },
  { key: 'aliases',   label: 'Aliases & attribution',      on: false },
] as const

function triggerDownload(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url; a.download = filename; a.click()
  URL.revokeObjectURL(url)
}

async function downloadRawCSV() {
  const r = await fetch('/api/stats')
  if (!r.ok) throw new Error('Failed to fetch stats')
  const { leaderboard } = await r.json()
  const rows = ['Song,Plays,Pct', ...leaderboard.map((e: { name: string; count: number; pct: number }) =>
    `"${e.name}",${e.count},${e.pct}`
  )]
  triggerDownload('steal-your-stats-leaderboard.csv', rows.join('\n'), 'text/csv')
}

async function generateDossierMD(songTitle: string, include: Record<string, boolean>) {
  const [factsRes, posRes, versRes] = await Promise.allSettled([
    fetch(`/api/song-facts?songTitle=${encodeURIComponent(songTitle)}`).then(r => r.json()),
    fetch(`/api/position-facts?songTitle=${encodeURIComponent(songTitle)}`).then(r => r.json()),
    fetch(`/api/versions?songTitle=${encodeURIComponent(songTitle)}`).then(r => r.json()),
  ])
  const facts = factsRes.status === 'fulfilled' ? factsRes.value : null
  const pos   = posRes.status === 'fulfilled'   ? posRes.value   : null
  const vers  = versRes.status === 'fulfilled'  ? versRes.value  : null

  const lines: string[] = []
  lines.push(`# ${songTitle} — Song Dossier`)
  lines.push(`*Generated by Steal Your Stats · ${new Date().toLocaleDateString()}*\n`)

  if (include.perf && facts) {
    lines.push('## Performance Facts')
    lines.push(`- **Total performances:** ${facts.totalPerformances}`)
    if (facts.first) lines.push(`- **First:** ${facts.first.date} · ${facts.first.venue}, ${facts.first.city}`)
    if (facts.last)  lines.push(`- **Last:** ${facts.last.date} · ${facts.last.venue}, ${facts.last.city}`)
    lines.push('')
  }
  if (include.position && pos) {
    lines.push('## Position Breakdown')
    lines.push(`| Position | Count |`)
    lines.push(`|---|---|`)
    lines.push(`| Opener | ${pos.opener?.count ?? 0} |`)
    lines.push(`| Closer | ${pos.closer?.count ?? 0} |`)
    lines.push(`| Encore | ${pos.encore?.count ?? 0} |`)
    lines.push('')
  }
  if (include.versions && vers?.tracks) {
    const top25 = vers.tracks.slice(0, 25)
    lines.push('## Versions (top 25)')
    lines.push('| Date | Venue | Duration |')
    lines.push('|---|---|---|')
    for (const t of top25) {
      const dur = t.durationSec
        ? `${Math.floor(t.durationSec / 60)}:${String(Math.floor(t.durationSec % 60)).padStart(2, '0')}`
        : '—'
      lines.push(`| ${t.showDate} | ${t.venue} | ${dur} |`)
    }
    lines.push('')
  }
  if (include.aliases && facts?.aliases?.length) {
    lines.push('## Aliases & Attribution')
    lines.push(facts.aliases.map((a: string) => `- ${a}`).join('\n'))
    lines.push('')
  }
  lines.push('## Provenance')
  lines.push('- Performance data: [setlist.fm](https://www.setlist.fm)')
  lines.push('- Audio: [Archive.org](https://archive.org)')
  lines.push('')
  lines.push(`---\n— end of dossier · steal your stats · ${new Date().toLocaleDateString()} —`)

  const slug = songTitle.toLowerCase().replace(/[^a-z0-9]+/g, '-')
  triggerDownload(`steal-your-stats-${slug}.md`, lines.join('\n'), 'text/markdown')
}

type Tab = 'builder' | 'data'

export default function ExportPage() {
  const [tab, setTab] = useState<Tab>('builder')
  const [include, setInclude] = useState<Record<string, boolean>>(() =>
    Object.fromEntries(DOSSIER_SECTIONS.map(s => [s.key, s.on]))
  )
  const [songInput, setSongInput] = useState('Dark Star')
  const [csvState,     setCsvState]     = useState<'idle' | 'loading' | 'done' | 'error'>('idle')
  const [dossierState, setDossierState] = useState<'idle' | 'loading' | 'done' | 'error'>('idle')

  const handleRawCSV = async () => {
    setCsvState('loading')
    try { await downloadRawCSV(); setCsvState('done') }
    catch { setCsvState('error') }
    setTimeout(() => setCsvState('idle'), 3000)
  }

  const handleDossier = async () => {
    if (!songInput.trim()) return
    setDossierState('loading')
    try { await generateDossierMD(songInput.trim(), include); setDossierState('done') }
    catch { setDossierState('error') }
    setTimeout(() => setDossierState('idle'), 3000)
  }

  const csvLabel = { idle: '↓ Download CSV', loading: 'Fetching…', done: 'Downloaded ✓', error: 'Error — retry' }
  const dossierLabel = { idle: '↓ Download .md', loading: 'Building…', done: 'Downloaded ✓', error: 'Error — retry' }

  return (
    <section className="col">
      <div className="page-head">
        <div>
          <div className="kicker">Export · IX</div>
          <h2>Build your <span className="italic">perfect set.</span></h2>
          <div className="lede">Compose a setlist, generate a song dossier, or pull raw CSV — leave the vault with something in hand.</div>
        </div>
      </div>

      {/* Tab bar */}
      <div className="export-tabs">
        <button
          className={`export-tab${tab === 'builder' ? ' active' : ''}`}
          onClick={() => setTab('builder')}
        >
          ≡ Setlist Builder
        </button>
        <button
          className={`export-tab${tab === 'data' ? ' active' : ''}`}
          onClick={() => setTab('data')}
        >
          ↓ Data Export
        </button>
      </div>

      {/* Setlist Builder tab */}
      {tab === 'builder' && <SetlistBuilder />}

      {/* Data Export tab */}
      {tab === 'data' && (
        <div style={{ display: 'grid', gridTemplateColumns: '320px 1fr', gap: 28, marginTop: 4 }}>

          {/* Left — builder controls */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>

            {/* Song Dossier */}
            <div style={{ border: '1.5px solid var(--ink)', padding: '18px 20px', background: 'var(--paper)', boxShadow: '3px 3px 0 var(--rule-soft)' }}>
              <div style={{ fontFamily: 'var(--mono)', fontSize: 10, letterSpacing: '0.16em', textTransform: 'uppercase', color: 'var(--ink-3)', marginBottom: 10 }}>Song Dossier — Markdown</div>
              <div style={{ fontFamily: 'var(--mono)', fontSize: 11, letterSpacing: '0.04em', color: 'var(--ink-3)', marginBottom: 6 }}>Choose a song</div>
              <div style={{ border: '1px solid var(--ink)', background: 'var(--paper)', display: 'flex', alignItems: 'center', gap: 8, padding: '6px 10px', marginBottom: 14 }}>
                <span style={{ color: 'var(--ink-3)' }}>⌕</span>
                <input
                  value={songInput}
                  onChange={e => setSongInput(e.target.value)}
                  placeholder="Song name…"
                  style={{ background: 'transparent', border: 0, outline: 'none', fontFamily: 'var(--mono)', fontSize: 12, flex: 1, color: 'var(--ink)' }}
                />
              </div>

              <div style={{ fontFamily: 'var(--mono)', fontSize: 10, letterSpacing: '0.16em', textTransform: 'uppercase', color: 'var(--ink-3)', marginBottom: 8 }}>Sections</div>
              {DOSSIER_SECTIONS.map(s => (
                <div
                  key={s.key}
                  onClick={() => setInclude(prev => ({ ...prev, [s.key]: !prev[s.key] }))}
                  style={{
                    display: 'flex', alignItems: 'center', gap: 10, padding: '6px 0',
                    borderBottom: '1px dotted var(--rule-soft)', cursor: 'pointer',
                  }}
                >
                  <span style={{
                    width: 14, height: 14, border: '1px solid var(--ink)',
                    background: include[s.key] ? 'var(--forest)' : 'var(--paper)',
                    color: 'var(--paper)', fontFamily: 'var(--mono)', fontSize: 10,
                    display: 'grid', placeItems: 'center', flexShrink: 0,
                  }}>
                    {include[s.key] ? '✓' : ''}
                  </span>
                  <span style={{
                    fontFamily: 'var(--serif-body)', fontSize: 14,
                    color: include[s.key] ? 'var(--ink)' : 'var(--ink-3)',
                  }}>{s.label}</span>
                </div>
              ))}

              <button
                className="btn primary"
                style={{ marginTop: 14, width: '100%', justifyContent: 'center' }}
                onClick={handleDossier}
                disabled={dossierState === 'loading' || !songInput.trim()}
              >
                {dossierLabel[dossierState]}
              </button>
            </div>

            {/* Raw Data */}
            <div style={{ border: '1.5px solid var(--ink)', padding: '18px 20px', background: 'var(--paper)', boxShadow: '3px 3px 0 var(--rule-soft)' }}>
              <div style={{ fontFamily: 'var(--mono)', fontSize: 10, letterSpacing: '0.16em', textTransform: 'uppercase', color: 'var(--ink-3)', marginBottom: 8 }}>Raw Data · CSV</div>
              <div style={{ fontFamily: 'var(--serif-body)', fontStyle: 'italic', fontSize: 13.5, color: 'var(--ink-2)', marginBottom: 12, lineHeight: 1.35 }}>
                All-time leaderboard — all 442 songs with counts and percentages. Re-importable into other archives.
              </div>
              <button
                className="btn ghost"
                style={{ width: '100%', justifyContent: 'center' }}
                onClick={handleRawCSV}
                disabled={csvState === 'loading'}
              >
                {csvLabel[csvState]}
              </button>
            </div>

            {/* Show Ticket — coming soon */}
            <div style={{ border: '1.5px dashed var(--rule)', padding: '18px 20px', opacity: 0.6 }}>
              <div style={{ fontFamily: 'var(--mono)', fontSize: 10, letterSpacing: '0.16em', textTransform: 'uppercase', color: 'var(--ink-3)', marginBottom: 8 }}>Show Ticket · PNG poster</div>
              <div style={{ fontFamily: 'var(--serif-body)', fontStyle: 'italic', fontSize: 13, color: 'var(--ink-3)' }}>
                coming in the next pressing.
              </div>
            </div>
          </div>

          {/* Right — live preview */}
          <div>
            <div style={{ fontFamily: 'var(--mono)', fontSize: 10, letterSpacing: '0.18em', textTransform: 'uppercase', color: 'var(--ink-3)', marginBottom: 8 }}>Live preview</div>
            <div style={{
              border: '1.5px solid var(--ink)',
              background: 'var(--paper)',
              padding: '28px 32px',
              boxShadow: '3px 3px 0 var(--rule-soft)',
              minHeight: 360,
              display: 'flex', flexDirection: 'column', gap: 14,
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 10, borderBottom: '1px solid var(--rule)', paddingBottom: 10 }}>
                <span style={{ fontFamily: 'var(--mono)', fontSize: 10, letterSpacing: '0.16em', textTransform: 'uppercase', color: 'var(--ink-3)', flex: 1 }}>
                  STEAL YOUR STATS · SONG DOSSIER
                </span>
                <span style={{ fontFamily: 'var(--mono)', fontSize: 9, color: 'var(--ink-3)' }}>MD</span>
              </div>

              <div>
                <div style={{ fontFamily: 'var(--serif-display)', fontSize: 36, letterSpacing: '-0.012em', color: 'var(--ink)', lineHeight: 1 }}>
                  {songInput || '—'}
                </div>
                <div style={{ fontFamily: 'var(--serif-body)', fontStyle: 'italic', fontSize: 14, color: 'var(--ink-3)' }}>
                  — a dossier
                </div>
              </div>

              <div style={{ fontFamily: 'var(--mono)', fontSize: 10, letterSpacing: '0.1em', color: 'var(--ink-3)', textTransform: 'uppercase' }}>
                compiled by the vault operator · MMXXVI
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
                {DOSSIER_SECTIONS.filter(s => include[s.key]).map(s => (
                  <div key={s.key} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                    <span style={{ width: 6, height: 6, background: 'var(--rust)', borderRadius: '50%', flexShrink: 0 }} />
                    <span style={{ fontFamily: 'var(--serif-body)', fontSize: 13, color: 'var(--ink-2)' }}>{s.label}</span>
                  </div>
                ))}
                {DOSSIER_SECTIONS.every(s => !include[s.key]) && (
                  <div style={{ fontFamily: 'var(--serif-body)', fontStyle: 'italic', fontSize: 13, color: 'var(--ink-3)' }}>
                    No sections selected.
                  </div>
                )}
              </div>

              <div style={{ marginTop: 'auto', borderTop: '1px solid var(--rule)', paddingTop: 10, fontFamily: 'var(--mono)', fontSize: 10, letterSpacing: '0.08em', color: 'var(--ink-3)', textTransform: 'uppercase' }}>
                — end of dossier · steal your stats, vol. xi ·{' '}
                {DOSSIER_SECTIONS.some(s => include[s.key]) ? 'complete' : 'empty'} —
              </div>
            </div>
          </div>
        </div>
      )}
    </section>
  )
}
