'use client'

import React, { useState } from 'react'
import { TopBar } from '@/components/glass/topbar'
import { Icon, ICONS } from '@/components/glass/icons'
import { SetlistBuilder } from './SetlistBuilder'

const SECTIONS = [
  ['Performance facts',          true],
  ['Position breakdown',          true],
  ['Versions table (top 25)',     true],
  ['Longest/shortest extremes',   true],
  ['Aliases & cross-references',  false],
  ['Setlist.fm provenance footer', false],
] as const

function triggerDownload(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

async function downloadRawCSV() {
  const r = await fetch('/api/stats')
  if (!r.ok) throw new Error('Failed to fetch stats')
  const { leaderboard } = await r.json()
  const rows = ['Song,Plays,Pct', ...leaderboard.map((e: { name: string; count: number; pct: number }) =>
    `"${e.name}",${e.count},${e.pct}`
  )]
  triggerDownload('steal-your-stats-leaderboard.csv', rows.join('\n'), 'text/csv')
}

async function generateDossierMD(songTitle: string, sections: boolean[]) {
  const [factsRes, posRes, versRes] = await Promise.allSettled([
    fetch(`/api/song-facts?songTitle=${encodeURIComponent(songTitle)}`).then(r => r.json()),
    fetch(`/api/position-facts?songTitle=${encodeURIComponent(songTitle)}`).then(r => r.json()),
    fetch(`/api/versions?songTitle=${encodeURIComponent(songTitle)}`).then(r => r.json()),
  ])

  const facts = factsRes.status === 'fulfilled' ? factsRes.value : null
  const pos   = posRes.status === 'fulfilled'   ? posRes.value   : null
  const vers  = versRes.status === 'fulfilled'  ? versRes.value  : null

  const lines: string[] = []
  lines.push(`# ${songTitle} — Song Dossier`)
  lines.push(`*Generated by Steal Your Stats · ${new Date().toLocaleDateString()}*\n`)

  if (sections[0] && facts) {
    lines.push('## Performance Facts')
    lines.push(`- **Total performances:** ${facts.totalPerformances}`)
    if (facts.first) lines.push(`- **First:** ${facts.first.date} · ${facts.first.venue}, ${facts.first.city}`)
    if (facts.last)  lines.push(`- **Last:** ${facts.last.date} · ${facts.last.venue}, ${facts.last.city}`)
    lines.push('')
  }

  if (sections[1] && pos) {
    lines.push('## Position Breakdown')
    lines.push(`| Position | Count |`)
    lines.push(`|---|---|`)
    lines.push(`| Opener | ${pos.opener.count} |`)
    lines.push(`| Closer | ${pos.closer.count} |`)
    lines.push(`| Encore | ${pos.encore.count} |`)
    lines.push('')
  }

  if (sections[2] && vers?.tracks) {
    const top25 = vers.tracks.slice(0, 25)
    lines.push('## Versions (top 25)')
    lines.push('| Date | Venue | Duration |')
    lines.push('|---|---|---|')
    for (const t of top25) {
      const dur = t.durationSec
        ? `${Math.floor(t.durationSec / 60)}:${String(Math.floor(t.durationSec % 60)).padStart(2, '0')}`
        : '—'
      lines.push(`| ${t.showDate} | ${t.venue} | ${dur} |`)
    }
    lines.push('')
  }

  if (sections[3] && vers?.extremes) {
    const { longest, shortest } = vers.extremes
    lines.push('## Extremes')
    if (longest?.durationSec) {
      const d = longest.durationSec
      lines.push(`- **Longest:** ${Math.floor(d / 60)}:${String(Math.floor(d % 60)).padStart(2, '0')} · ${longest.showDate} · ${longest.venue}`)
    }
    if (shortest?.durationSec) {
      const d = shortest.durationSec
      lines.push(`- **Shortest:** ${Math.floor(d / 60)}:${String(Math.floor(d % 60)).padStart(2, '0')} · ${shortest.showDate} · ${shortest.venue}`)
    }
    lines.push('')
  }

  if (sections[4] && facts?.aliases?.length) {
    lines.push('## Aliases')
    lines.push(facts.aliases.map((a: string) => `- ${a}`).join('\n'))
    lines.push('')
  }

  if (sections[5]) {
    lines.push('## Provenance')
    lines.push('- Performance data: [setlist.fm](https://www.setlist.fm)')
    lines.push('- Audio: [Archive.org](https://archive.org)')
    lines.push('')
  }

  const slug = songTitle.toLowerCase().replace(/[^a-z0-9]+/g, '-')
  triggerDownload(`steal-your-stats-${slug}.md`, lines.join('\n'), 'text/markdown')
}

type Tab = 'export' | 'setlist'

export default function ExportPage() {
  const [tab, setTab] = useState<Tab>('export')
  const [sections, setSections] = useState<boolean[]>(SECTIONS.map(([, on]) => on))
  const [format, setFormat] = useState('MD')
  const [songInput, setSongInput] = useState('Dark Star')
  const [csvState,     setCsvState]     = useState<'idle' | 'loading' | 'done' | 'error'>('idle')
  const [dossierState, setDossierState] = useState<'idle' | 'loading' | 'done' | 'error'>('idle')

  const handleRawCSV = async () => {
    setCsvState('loading')
    try {
      await downloadRawCSV()
      setCsvState('done')
    } catch {
      setCsvState('error')
    }
    setTimeout(() => setCsvState('idle'), 3000)
  }

  const handleDossier = async () => {
    if (!songInput.trim()) return
    setDossierState('loading')
    try {
      await generateDossierMD(songInput.trim(), sections)
      setDossierState('done')
    } catch {
      setDossierState('error')
    }
    setTimeout(() => setDossierState('idle'), 3000)
  }

  const csvLabel = { idle: 'Download CSV', loading: 'Fetching…', done: 'Downloaded ✓', error: 'Error — retry' }
  const dossierLabel = { idle: `Generate dossier`, loading: 'Building…', done: 'Downloaded ✓', error: 'Error — retry' }

  return (
    <>
      <TopBar
        eyebrow="Export"
        title={tab === 'export' ? 'Pull your data, share a setlist.' : 'Build your perfect set.'}
      />

      <div className="scroll-hide" style={{ flex: 1, overflow: 'auto', padding: '0 28px 24px', display: 'flex', flexDirection: 'column', gap: 18 }}>

        {/* Tab switcher */}
        <div style={{ display: 'flex', gap: 6 }}>
          {([
            { key: 'export' as Tab,   icon: ICONS.download, label: 'Data Export' },
            { key: 'setlist' as Tab,  icon: ICONS.list,     label: 'Setlist Builder' },
          ]).map(({ key, icon, label }) => (
            <button
              key={key}
              onClick={() => setTab(key)}
              className={`btn${tab === key ? ' primary' : ''}`}
              style={{ gap: 7 }}
            >
              <Icon d={icon} size={13} />
              {label}
            </button>
          ))}
        </div>

        {/* ── Data Export tab ──────────────────────────────────────────────── */}
        {tab === 'export' && (
          <>
            {/* Quick exports */}
            <section style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 14 }}>
              {/* Song dossier */}
              <div className="glass" style={{ padding: '20px 22px', display: 'flex', flexDirection: 'column', gap: 12 }}>
                <div style={{ width: 38, height: 38, borderRadius: 'var(--r-sm)', background: 'var(--glass-bg-strong)', color: 'var(--fg-2)', display: 'flex', alignItems: 'center', justifyContent: 'center', border: '1px solid var(--glass-border)' }}>
                  <Icon d={ICONS.music} size={17} />
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
                  <h3 className="t-h3" style={{ fontSize: 18 }}>Song dossier</h3>
                  <span className="t-eyebrow">MD · Markdown</span>
                </div>
                <p className="t-body" style={{ fontSize: 13 }}>Performance facts, position breakdown, and the versions table for any song.</p>
                <button className="btn" style={{ alignSelf: 'flex-start', marginTop: 4 }} onClick={() => document.getElementById('builder-section')?.scrollIntoView({ behavior: 'smooth' })}>
                  <Icon d={ICONS.download} size={13} /> Build dossier
                </button>
              </div>

              {/* Show ticket */}
              <div className="glass strong" style={{ padding: '20px 22px', display: 'flex', flexDirection: 'column', gap: 12, boxShadow: 'var(--shadow-card), 0 0 0 1px rgba(240,176,74,0.3)' }}>
                <div style={{ width: 38, height: 38, borderRadius: 'var(--r-sm)', background: 'var(--accent-soft)', color: 'var(--accent)', display: 'flex', alignItems: 'center', justifyContent: 'center', border: '1px solid var(--glass-border)' }}>
                  <Icon d={ICONS.calendar} size={17} />
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
                  <h3 className="t-h3" style={{ fontSize: 18 }}>Show ticket</h3>
                  <span className="t-eyebrow">PNG · 1080 × 1920 · coming soon</span>
                </div>
                <p className="t-body" style={{ fontSize: 13 }}>A sharable poster for any show — date, venue, setlist, and a QR back to the tape.</p>
                <button className="btn primary" style={{ alignSelf: 'flex-start', marginTop: 4 }} disabled>
                  <Icon d={ICONS.download} size={13} /> Design ticket
                </button>
              </div>

              {/* Raw data */}
              <div className="glass" style={{ padding: '20px 22px', display: 'flex', flexDirection: 'column', gap: 12 }}>
                <div style={{ width: 38, height: 38, borderRadius: 'var(--r-sm)', background: 'var(--glass-bg-strong)', color: 'var(--fg-2)', display: 'flex', alignItems: 'center', justifyContent: 'center', border: '1px solid var(--glass-border)' }}>
                  <Icon d={ICONS.download} size={17} />
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
                  <h3 className="t-h3" style={{ fontSize: 18 }}>Raw data</h3>
                  <span className="t-eyebrow">CSV · all-time leaderboard</span>
                </div>
                <p className="t-body" style={{ fontSize: 13 }}>Song names + all-time play counts from the setlist cache. Re-importable into other archives.</p>
                <button
                  className="btn"
                  style={{ alignSelf: 'flex-start', marginTop: 4, color: csvState === 'done' ? 'var(--accent)' : undefined }}
                  onClick={handleRawCSV}
                  disabled={csvState === 'loading'}
                >
                  <Icon d={ICONS.download} size={13} /> {csvLabel[csvState]}
                </button>
              </div>
            </section>

            {/* Builder + preview */}
            <section id="builder-section" style={{ display: 'grid', gridTemplateColumns: '1fr 1.1fr', gap: 18 }}>
              {/* Builder */}
              <div className="glass" style={{ padding: '22px 24px', display: 'flex', flexDirection: 'column', gap: 18 }}>
                <header style={{ display: 'flex', alignItems: 'baseline', gap: 10 }}>
                  <h3 className="t-h3">Build · Song dossier</h3>
                  <span className="t-eyebrow">Markdown export</span>
                </header>

                <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                  <span className="t-eyebrow">Subject</span>
                  <div className="glass faint" style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '8px 12px', borderRadius: 'var(--r-sm)' }}>
                    <Icon d={ICONS.search} size={12} />
                    <input
                      value={songInput}
                      onChange={e => setSongInput(e.target.value)}
                      placeholder="Song name…"
                      style={{ background: 'transparent', border: 0, outline: 'none', color: 'var(--fg)', fontSize: 13, flex: 1 }}
                    />
                  </div>
                </div>

                <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                  <span className="t-eyebrow">Sections</span>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                    {SECTIONS.map(([label], i) => (
                      <label key={label} style={{ display: 'flex', alignItems: 'center', gap: 12, cursor: 'pointer', padding: '4px 0' }}>
                        <span
                          className={`toggle ${sections[i] ? 'on' : 'off'}`}
                          onClick={() => setSections(prev => prev.map((v, j) => j === i ? !v : v))}
                        />
                        <span style={{ fontSize: 13, color: sections[i] ? 'var(--fg)' : 'var(--fg-3)' }}>{label}</span>
                      </label>
                    ))}
                  </div>
                </div>

                <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                  <span className="t-eyebrow">Format</span>
                  <div style={{ display: 'flex', gap: 6 }}>
                    {(['MD', 'PDF', 'PNG'] as const).map(f => (
                      <span
                        key={f}
                        className={`pill${format === f ? ' accent' : ''}`}
                        style={{ padding: '6px 14px', cursor: 'pointer' }}
                        onClick={() => setFormat(f)}
                      >
                        {f}{f !== 'MD' ? ' (soon)' : ''}
                      </span>
                    ))}
                  </div>
                </div>

                <div className="divider" />

                <div style={{ display: 'flex', gap: 8 }}>
                  <button
                    className="btn primary lg"
                    style={{ flex: 1, justifyContent: 'center' }}
                    onClick={handleDossier}
                    disabled={dossierState === 'loading' || format !== 'MD' || !songInput.trim()}
                  >
                    <Icon d={ICONS.download} size={14} />
                    {format !== 'MD' ? 'MD format required' : dossierLabel[dossierState]}
                  </button>
                </div>
              </div>

              {/* Preview */}
              <div className="glass" style={{ padding: '22px 24px', display: 'flex', flexDirection: 'column', gap: 14 }}>
                <header style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                  <h3 className="t-h3">Preview</h3>
                  <span className="t-eyebrow">{songInput || 'no song selected'}</span>
                </header>

                <div style={{
                  aspectRatio: '210 / 297',
                  background: '#f4f1ea', color: '#1a1f3a',
                  borderRadius: 'var(--r-md)',
                  padding: '32px 36px',
                  boxShadow: '0 18px 50px -14px rgba(0,0,0,0.6), inset 0 0 0 1px rgba(255,255,255,0.1)',
                  display: 'flex', flexDirection: 'column', gap: 14,
                  fontFamily: 'var(--font-sans)',
                  overflow: 'hidden',
                }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 10, borderBottom: '1px solid #1a1f3a22', paddingBottom: 12 }}>
                    <svg width="22" height="22" viewBox="0 0 40 40">
                      <path d="M22 8 L12 22 L19 22 L17 32 L28 17 L21 17 Z" fill="#c97a0c" />
                    </svg>
                    <span style={{ fontSize: 10, letterSpacing: '0.2em', textTransform: 'uppercase', color: '#1a1f3a99' }}>
                      STEAL YOUR STATS · SONG DOSSIER
                    </span>
                    <span style={{ flex: 1 }} />
                    <span style={{ fontSize: 9, fontFamily: 'var(--font-mono)', color: '#1a1f3a99' }}>MD</span>
                  </div>

                  <h2 style={{ fontSize: 32, letterSpacing: '-0.025em', margin: 0, fontWeight: 600, color: '#1a1f3a', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                    {songInput || '—'}
                  </h2>
                  <span style={{ fontSize: 10.5, color: '#1a1f3a99', fontFamily: 'var(--font-mono)', letterSpacing: '0.05em' }}>
                    Sections: {sections.filter(Boolean).length} of {SECTIONS.length} selected
                  </span>

                  <div style={{ display: 'flex', flexDirection: 'column', gap: 6, marginTop: 8 }}>
                    {SECTIONS.map(([label], i) => sections[i] && (
                      <div key={label} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                        <span style={{ width: 6, height: 6, borderRadius: '50%', background: '#c97a0c', flexShrink: 0 }} />
                        <span style={{ fontSize: 11, color: '#1a1f3a', fontFamily: 'var(--font-sans)' }}>{label}</span>
                      </div>
                    ))}
                  </div>

                  <div style={{
                    background: '#c97a0c11', border: '1px solid #c97a0c44', borderRadius: 8,
                    padding: 12, marginTop: 'auto',
                  }}>
                    <div style={{ fontSize: 8, letterSpacing: '0.15em', color: '#c97a0c', textTransform: 'uppercase' }}>FORMAT</div>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: 18, color: '#c97a0c', letterSpacing: '-0.02em' }}>Markdown (.md)</div>
                    <div style={{ fontSize: 10, color: '#1a1f3a99' }}>Renders in GitHub, Obsidian, Notion…</div>
                  </div>
                </div>
              </div>
            </section>
          </>
        )}

        {/* ── Setlist Builder tab ──────────────────────────────────────────── */}
        {tab === 'setlist' && <SetlistBuilder />}
      </div>
    </>
  )
}
