'use client'

import React, { useState, useRef, useEffect, useCallback } from 'react'
import { Icon, ICONS } from '@/components/glass/icons'
import {
  makeEntry, formatDurationShort, totalDuration,
  EMPTY_SETLIST, SETLIST_STORAGE_KEY,
  type SetKey, type SetlistEntry, type SetlistState, type SongHints,
} from '@/lib/setlist-builder'
import { toTitleCase } from '@/lib/utils'

// ─── Helpers ──────────────────────────────────────────────────────────────────

function useDebounce<T>(value: T, delay: number): T {
  const [debounced, setDebounced] = useState(value)
  useEffect(() => {
    const t = setTimeout(() => setDebounced(value), delay)
    return () => clearTimeout(t)
  }, [value, delay])
  return debounced
}

function fmtTotal(secs: number): string {
  if (secs === 0) return '—'
  const h = Math.floor(secs / 3600)
  const m = Math.floor((secs % 3600) / 60)
  if (h > 0) return `~${h}h ${m}m`
  return `~${m} min`
}

// ─── PDF export ───────────────────────────────────────────────────────────────

function generatePrintHTML(sl: SetlistState): string {
  const renderSet = (songs: SetlistEntry[], label: string) => {
    if (songs.length === 0) return ''
    return `
      <div class="set">
        <div class="set-label">${label}</div>
        ${songs.map((s, i) => `
          <div class="song${s.segueIntoNext ? ' segue' : ''}">
            <span class="num">${i + 1}.</span>
            <span class="title">${toTitleCase(s.displayTitle)}</span>
            ${s.segueIntoNext ? '<span class="arr">&#8594;</span>' : ''}
            ${s.durationSec ? `<span class="dur">~${formatDurationShort(s.durationSec)}</span>` : ''}
          </div>
        `).join('')}
        <div class="set-total">Est. ${fmtTotal(totalDuration(songs))}</div>
      </div>`
  }

  const allSongs = [...sl.set1, ...sl.set2, ...sl.encore]
  const grandTotal = fmtTotal(totalDuration(allSongs))

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Set List</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Courier New', Courier, monospace; background: #fff; color: #111; padding: 48px 56px; max-width: 640px; }
  .header { border-bottom: 3px solid #111; padding-bottom: 18px; margin-bottom: 28px; }
  .band { font-size: 30px; font-weight: 900; text-transform: uppercase; letter-spacing: 0.04em; line-height: 1; }
  .meta { font-size: 13px; margin-top: 8px; color: #444; letter-spacing: 0.04em; }
  .set { margin-bottom: 28px; page-break-inside: avoid; }
  .set-label { font-size: 10px; font-weight: 900; letter-spacing: 0.25em; text-transform: uppercase;
    border-bottom: 1px solid #999; padding-bottom: 5px; margin-bottom: 10px; color: #555; }
  .song { display: flex; align-items: baseline; gap: 10px; padding: 5px 0;
    font-size: 17px; border-bottom: 1px dotted #ddd; }
  .num { width: 26px; color: #999; font-size: 12px; flex-shrink: 0; }
  .title { flex: 1; font-weight: 600; }
  .arr { color: #555; font-size: 14px; }
  .dur { color: #999; font-size: 11px; font-family: inherit; white-space: nowrap; }
  .set-total { font-size: 10px; color: #999; text-align: right; margin-top: 6px; letter-spacing: 0.1em; }
  .grand-total { font-size: 11px; color: #555; border-top: 2px solid #111; padding-top: 10px; margin-top: 4px; letter-spacing: 0.1em; }
  .footer { margin-top: 36px; font-size: 10px; color: #aaa; border-top: 1px solid #ddd; padding-top: 10px; }
  @media print { body { padding: 24px 32px; } }
</style></head><body>
  <div class="header">
    <div class="band">${sl.bandName || 'Set List'}</div>
    <div class="meta">${[sl.date, sl.venue].filter(Boolean).join(' · ')}</div>
  </div>
  ${renderSet(sl.set1, 'Set I')}
  ${renderSet(sl.set2, 'Set II')}
  ${renderSet(sl.encore, 'Encore')}
  ${allSongs.length > 0 ? `<div class="grand-total">Total estimated runtime: ${grandTotal}</div>` : ''}
  <div class="footer">Generated by Steal Your Stats &middot; ${new Date().toLocaleDateString()}</div>
</body></html>`
}

// ─── Drag state ───────────────────────────────────────────────────────────────

interface DragSource { setKey: SetKey; idx: number }

// ─── Sub-components ───────────────────────────────────────────────────────────

interface SongResultProps {
  displayTitle: string
  hints: SongHints
  onAdd: () => void
  isDuplicate: boolean
}

function SongResult({ displayTitle, hints, onAdd, isDuplicate }: SongResultProps) {
  const { pairing, positionHints, avgDurationSec } = hints

  return (
    <div style={{
      display: 'flex', flexDirection: 'column', gap: 6,
      padding: '10px 14px',
      borderRadius: 'var(--r-sm)',
      border: isDuplicate ? '1px solid rgba(255,138,138,0.3)' : '1px solid transparent',
      background: isDuplicate ? 'rgba(255,138,138,0.06)' : 'transparent',
      transition: 'background 0.12s',
    }}
      onMouseEnter={e => { if (!isDuplicate) e.currentTarget.style.background = 'var(--glass-bg)' }}
      onMouseLeave={e => { if (!isDuplicate) e.currentTarget.style.background = 'transparent' }}
    >
      <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
        <span style={{ flex: 1, fontSize: 13.5, fontWeight: 500, color: 'var(--fg)' }}>
          {toTitleCase(displayTitle)}
        </span>
        {avgDurationSec && (
          <span className="t-mono" style={{ fontSize: 10.5, color: 'var(--fg-4)' }}>
            ~{formatDurationShort(avgDurationSec)}
          </span>
        )}
        <button
          className="btn"
          onClick={onAdd}
          disabled={isDuplicate}
          style={{ padding: '4px 10px', fontSize: 11.5, gap: 4, opacity: isDuplicate ? 0.4 : 1 }}
        >
          <Icon d={ICONS.plus} size={11} />
          {isDuplicate ? 'Added' : 'Add'}
        </button>
      </div>

      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
        {pairing && (
          <span className="pill" style={{
            fontSize: 10.5, padding: '2px 8px',
            background: pairing.alwaysWith ? 'rgba(240,176,74,0.12)' : 'var(--glass-bg-faint)',
            borderColor: pairing.alwaysWith ? 'rgba(240,176,74,0.28)' : 'var(--glass-border)',
            color: pairing.alwaysWith ? 'var(--accent)' : 'var(--fg-3)',
          }}>
            {pairing.label}
          </span>
        )}
        {positionHints.isCommonOpener && (
          <span className="pill" style={{ fontSize: 10.5, padding: '2px 8px', color: 'var(--good)', borderColor: 'rgba(140,224,168,0.25)', background: 'rgba(140,224,168,0.07)' }}>
            Common opener
          </span>
        )}
        {positionHints.isCommonCloser && (
          <span className="pill" style={{ fontSize: 10.5, padding: '2px 8px', color: 'var(--warn)', borderColor: 'rgba(255,209,106,0.25)', background: 'rgba(255,209,106,0.07)' }}>
            Common closer
          </span>
        )}
        {positionHints.isCommonEncore && (
          <span className="pill" style={{ fontSize: 10.5, padding: '2px 8px', color: 'var(--fg-3)', borderColor: 'var(--glass-border)' }}>
            Encore song
          </span>
        )}
      </div>
    </div>
  )
}

interface SetSectionProps {
  label: string
  setKey: SetKey
  songs: SetlistEntry[]
  dragSource: React.MutableRefObject<DragSource | null>
  dropTarget: { setKey: SetKey; idx: number } | null
  onDragOver: (e: React.DragEvent, setKey: SetKey, idx: number) => void
  onDrop: (e: React.DragEvent, setKey: SetKey, idx: number) => void
  onDragLeave: () => void
  onDragStart: (setKey: SetKey, idx: number) => void
  onDragEnd: () => void
  onToggleSegue: (setKey: SetKey, idx: number) => void
  onRemove: (setKey: SetKey, idx: number) => void
  accentColor?: string
}

function SetSection({
  label, setKey, songs,
  dragSource, dropTarget,
  onDragOver, onDrop, onDragLeave, onDragStart, onDragEnd,
  onToggleSegue, onRemove, accentColor,
}: SetSectionProps) {
  const estTotal = totalDuration(songs)

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 0 }}>
      {/* Section header */}
      <div style={{
        display: 'flex', alignItems: 'center', gap: 10,
        padding: '8px 14px 6px',
        borderBottom: '1px solid var(--glass-border)',
      }}>
        <span className="t-eyebrow" style={{ color: accentColor ?? 'var(--fg-3)', flex: 1 }}>{label}</span>
        {songs.length > 0 && (
          <span className="t-mono" style={{ fontSize: 10.5, color: 'var(--fg-4)' }}>
            {songs.length} song{songs.length !== 1 ? 's' : ''} · {fmtTotal(estTotal)}
          </span>
        )}
      </div>

      {/* Drop zone (empty state) */}
      {songs.length === 0 && (
        <div
          onDragOver={e => onDragOver(e, setKey, 0)}
          onDrop={e => onDrop(e, setKey, 0)}
          onDragLeave={onDragLeave}
          style={{
            padding: '16px 14px',
            textAlign: 'center',
            color: 'var(--fg-4)',
            fontSize: 12,
            borderRadius: 'var(--r-sm)',
            border: dropTarget?.setKey === setKey ? '1px dashed var(--accent)' : '1px dashed transparent',
            margin: '4px 8px',
            transition: 'border-color 0.12s',
          }}
        >
          Search songs and add them here
        </div>
      )}

      {/* Song rows */}
      {songs.map((song, i) => {
        const isDropBefore = dropTarget?.setKey === setKey && dropTarget?.idx === i
        const isDragging = dragSource.current?.setKey === setKey && dragSource.current?.idx === i

        return (
          <React.Fragment key={song.id}>
            {/* Drop indicator line */}
            {isDropBefore && (
              <div style={{
                height: 2, background: 'var(--accent)',
                margin: '0 14px', borderRadius: 1,
                boxShadow: '0 0 8px var(--accent)',
              }} />
            )}

            <div
              draggable
              onDragStart={() => onDragStart(setKey, i)}
              onDragEnd={onDragEnd}
              onDragOver={e => onDragOver(e, setKey, i)}
              onDrop={e => onDrop(e, setKey, i)}
              onDragLeave={onDragLeave}
              style={{
                display: 'flex', alignItems: 'center', gap: 8,
                padding: '8px 14px',
                opacity: isDragging ? 0.4 : 1,
                transition: 'opacity 0.12s',
                cursor: 'grab',
              }}
            >
              {/* Drag handle + number */}
              <span className="t-mono" style={{ fontSize: 11, color: 'var(--fg-4)', width: 20, flexShrink: 0, textAlign: 'right' }}>
                {i + 1}
              </span>

              {/* Grip icon */}
              <span style={{ color: 'var(--fg-4)', flexShrink: 0, cursor: 'grab' }}>
                <Icon d={ICONS.list} size={12} />
              </span>

              {/* Title */}
              <span style={{ flex: 1, fontSize: 13, color: 'var(--fg)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                {song.displayTitle}
              </span>

              {/* Duration */}
              {song.durationSec && (
                <span className="t-mono" style={{ fontSize: 10.5, color: 'var(--fg-4)', flexShrink: 0 }}>
                  ~{formatDurationShort(song.durationSec)}
                </span>
              )}

              {/* Segue toggle */}
              <button
                onClick={() => onToggleSegue(setKey, i)}
                title={song.segueIntoNext ? 'Remove segue →' : 'Mark as segue →'}
                style={{
                  background: song.segueIntoNext ? 'var(--accent-soft)' : 'transparent',
                  border: `1px solid ${song.segueIntoNext ? 'rgba(240,176,74,0.35)' : 'var(--glass-border)'}`,
                  borderRadius: 'var(--r-full)',
                  padding: '2px 8px',
                  cursor: 'pointer',
                  fontSize: 11,
                  color: song.segueIntoNext ? 'var(--accent)' : 'var(--fg-4)',
                  fontFamily: 'var(--font-mono)',
                  transition: 'all 0.12s',
                  flexShrink: 0,
                }}
              >
                →
              </button>

              {/* Remove */}
              <button
                onClick={() => onRemove(setKey, i)}
                style={{ background: 'transparent', border: 0, cursor: 'pointer', color: 'var(--fg-4)', padding: 2, flexShrink: 0, display: 'flex' }}
                title="Remove"
              >
                <Icon d={ICONS.close} size={12} />
              </button>
            </div>

            {/* Segue connector line */}
            {song.segueIntoNext && i < songs.length - 1 && (
              <div style={{ display: 'flex', alignItems: 'center', padding: '0 14px 0 42px', gap: 6 }}>
                <div style={{ width: 1, height: 14, background: 'var(--accent)', opacity: 0.5 }} />
                <span style={{ fontSize: 10, color: 'var(--accent)', fontFamily: 'var(--font-mono)', opacity: 0.7 }}>→</span>
              </div>
            )}
          </React.Fragment>
        )
      })}

      {/* Drop zone at end of non-empty list */}
      {songs.length > 0 && (
        <div
          onDragOver={e => onDragOver(e, setKey, songs.length)}
          onDrop={e => onDrop(e, setKey, songs.length)}
          onDragLeave={onDragLeave}
          style={{
            height: 12,
            borderRadius: 'var(--r-xs)',
            border: dropTarget?.setKey === setKey && dropTarget?.idx === songs.length
              ? '1px dashed var(--accent)'
              : '1px dashed transparent',
            margin: '2px 8px',
            transition: 'border-color 0.12s',
          }}
        />
      )}
    </div>
  )
}

// ─── Main component ───────────────────────────────────────────────────────────

interface SearchSong {
  title: string
  displayTitle: string
  aliases: string[]
  hints: SongHints
}

export function SetlistBuilder() {
  // Setlist state
  const [setlist, setSetlist] = useState<SetlistState>(EMPTY_SETLIST)
  const [activeSet, setActiveSet] = useState<SetKey>('set1')
  const [loaded, setLoaded] = useState(false)

  // Search state
  const [query, setQuery] = useState('')
  const [results, setResults] = useState<SearchSong[]>([])
  const [searching, setSearching] = useState(false)
  const [querySinceLastAdd, setQuerySinceLastAdd] = useState(false)
  const debouncedQuery = useDebounce(query, 220)

  // Drag state
  const dragSource = useRef<DragSource | null>(null)
  const [dropTarget, setDropTarget] = useState<{ setKey: SetKey; idx: number } | null>(null)

  // Export state
  const [exporting, setExporting] = useState(false)

  // ── Load from localStorage ──────────────────────────────────────────────────
  useEffect(() => {
    try {
      const saved = localStorage.getItem(SETLIST_STORAGE_KEY)
      if (saved) setSetlist(JSON.parse(saved))
    } catch { /* ignore */ }
    setLoaded(true)
  }, [])

  // ── Save to localStorage ────────────────────────────────────────────────────
  useEffect(() => {
    if (!loaded) return
    try {
      localStorage.setItem(SETLIST_STORAGE_KEY, JSON.stringify(setlist))
    } catch { /* ignore */ }
  }, [setlist, loaded])

  // ── Song search ─────────────────────────────────────────────────────────────
  useEffect(() => {
    if (!debouncedQuery.trim()) { setResults([]); setQuerySinceLastAdd(false); return }
    setSearching(true)
    setQuerySinceLastAdd(true)
    fetch(`/api/songs?q=${encodeURIComponent(debouncedQuery)}`)
      .then(r => r.ok ? r.json() : null)
      .then(data => { if (data?.songs) setResults(data.songs.slice(0, 8)) })
      .catch(() => {})
      .finally(() => setSearching(false))
  }, [debouncedQuery])

  // ── Derived ─────────────────────────────────────────────────────────────────
  const allTitles = new Set([
    ...setlist.set1.map(e => e.title),
    ...setlist.set2.map(e => e.title),
    ...setlist.encore.map(e => e.title),
  ])

  // ── Setlist mutations ────────────────────────────────────────────────────────
  const addSong = useCallback((song: SearchSong) => {
    const entry = makeEntry(song.title)
    setSetlist(prev => ({ ...prev, [activeSet]: [...prev[activeSet], entry] }))
    setQuerySinceLastAdd(false)
  }, [activeSet])

  const removeSong = useCallback((setKey: SetKey, idx: number) => {
    setSetlist(prev => {
      const list = [...prev[setKey]]
      list.splice(idx, 1)
      return { ...prev, [setKey]: list }
    })
  }, [])

  const toggleSegue = useCallback((setKey: SetKey, idx: number) => {
    setSetlist(prev => {
      const list = [...prev[setKey]]
      list[idx] = { ...list[idx], segueIntoNext: !list[idx].segueIntoNext }
      return { ...prev, [setKey]: list }
    })
  }, [])

  const clearSetlist = useCallback(() => {
    setSetlist(EMPTY_SETLIST)
  }, [])

  // ── Drag and drop ────────────────────────────────────────────────────────────
  const onDragStart = useCallback((setKey: SetKey, idx: number) => {
    dragSource.current = { setKey, idx }
  }, [])

  const onDragEnd = useCallback(() => {
    dragSource.current = null
    setDropTarget(null)
  }, [])

  const onDragOver = useCallback((e: React.DragEvent, setKey: SetKey, idx: number) => {
    e.preventDefault()
    setDropTarget({ setKey, idx })
  }, [])

  const onDragLeave = useCallback(() => {
    // Don't clear immediately to avoid flicker
  }, [])

  const onDrop = useCallback((e: React.DragEvent, destKey: SetKey, destIdx: number) => {
    e.preventDefault()
    const src = dragSource.current
    if (!src) return

    setSetlist(prev => {
      const result = {
        ...prev,
        set1: [...prev.set1],
        set2: [...prev.set2],
        encore: [...prev.encore],
      }
      const srcList = result[src.setKey]
      const [item] = srcList.splice(src.idx, 1)

      const destList = result[destKey]
      const insertAt = src.setKey === destKey && destIdx > src.idx
        ? Math.max(0, destIdx - 1)
        : destIdx
      destList.splice(Math.min(insertAt, destList.length), 0, item)

      return result
    })

    dragSource.current = null
    setDropTarget(null)
  }, [])

  // ── PDF export ───────────────────────────────────────────────────────────────
  const handleExportPDF = useCallback(async () => {
    setExporting(true)
    try {
      const html = generatePrintHTML(setlist)
      const win = window.open('', '_blank', 'width=700,height=900')
      if (win) {
        win.document.write(html)
        win.document.close()
        win.focus()
        setTimeout(() => { win.print() }, 600)
      }
    } finally {
      setTimeout(() => setExporting(false), 1000)
    }
  }, [setlist])

  // ── Counts ───────────────────────────────────────────────────────────────────
  const totalSongs = setlist.set1.length + setlist.set2.length + setlist.encore.length
  const grandTotal = totalDuration([...setlist.set1, ...setlist.set2, ...setlist.encore])

  const SET_LABELS: Record<SetKey, string> = { set1: 'Set I', set2: 'Set II', encore: 'Encore' }

  return (
    <div style={{ display: 'grid', gridTemplateColumns: '340px 1fr', gap: 18, alignItems: 'start' }}>

      {/* ── Left: Search panel ──────────────────────────────────────────────── */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>

        {/* Search input */}
        <div className="glass" style={{ padding: '14px 16px', display: 'flex', flexDirection: 'column', gap: 10 }}>
          <span className="t-eyebrow">Search songs</span>
          <div className="glass faint" style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '8px 12px', borderRadius: 'var(--r-sm)' }}>
            <Icon d={ICONS.search} size={13} />
            <input
              value={query}
              onChange={e => setQuery(e.target.value)}
              placeholder="China Cat, Dark Star, Bertha…"
              autoFocus
              style={{ background: 'transparent', border: 0, outline: 'none', color: 'var(--fg)', fontSize: 13, flex: 1 }}
            />
            {searching && (
              <span style={{ fontSize: 10, color: 'var(--fg-4)' }}>…</span>
            )}
            {query && !searching && (
              <button onClick={() => { setQuery(''); setResults([]) }} style={{ background: 'none', border: 0, cursor: 'pointer', color: 'var(--fg-4)', display: 'flex', padding: 0 }}>
                <Icon d={ICONS.close} size={12} />
              </button>
            )}
          </div>

          {/* Add to set selector */}
          <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
            <span style={{ fontSize: 11, color: 'var(--fg-4)' }}>Add to:</span>
            {(['set1', 'set2', 'encore'] as SetKey[]).map(k => (
              <button
                key={k}
                onClick={() => setActiveSet(k)}
                className="pill"
                style={{
                  fontSize: 11, padding: '3px 10px', cursor: 'pointer',
                  background: activeSet === k ? 'var(--accent-soft)' : 'var(--glass-bg-faint)',
                  borderColor: activeSet === k ? 'rgba(240,176,74,0.35)' : 'var(--glass-border)',
                  color: activeSet === k ? 'var(--accent)' : 'var(--fg-3)',
                }}
              >
                {SET_LABELS[k]}
              </button>
            ))}
          </div>
        </div>

        {/* Results */}
        {results.length > 0 && (
          <div className="glass" style={{ padding: '6px 0', display: 'flex', flexDirection: 'column' }}>
            {results.map(song => (
              <SongResult
                key={song.title}
                displayTitle={song.displayTitle}
                hints={song.hints}
                onAdd={() => addSong(song)}
                isDuplicate={allTitles.has(song.title)}
              />
            ))}
          </div>
        )}

        {query && !searching && results.length === 0 && (
          <div className="glass" style={{ padding: '20px 16px', textAlign: 'center' }}>
            <span className="t-small">No songs found for &ldquo;{query}&rdquo;</span>
            <div style={{ marginTop: 10 }}>
              <button
                className="btn"
                style={{ fontSize: 12, padding: '6px 14px' }}
                onClick={() => {
                  const entry = makeEntry(query.trim())
                  setSetlist(prev => ({ ...prev, [activeSet]: [...prev[activeSet], entry] }))
                  setQuery('')
                  setResults([])
                }}
              >
                <Icon d={ICONS.plus} size={12} /> Add &ldquo;{query}&rdquo; anyway
              </button>
            </div>
          </div>
        )}

        {/* Pairing legend */}
        {!query && (
          <div className="glass faint" style={{ padding: '12px 14px', display: 'flex', flexDirection: 'column', gap: 8 }}>
            <span className="t-eyebrow">Legend</span>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}>
              {[
                { color: 'var(--accent)', label: 'Golden badge = almost always played together' },
                { color: 'var(--good)', label: 'Green = common set opener' },
                { color: 'var(--warn)', label: 'Yellow = common set closer' },
                { color: 'var(--fg-3)', label: 'Grey = common encore' },
              ].map(({ color, label }) => (
                <div key={label} style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                  <div style={{ width: 6, height: 6, borderRadius: '50%', background: color, flexShrink: 0 }} />
                  <span style={{ fontSize: 11, color: 'var(--fg-4)' }}>{label}</span>
                </div>
              ))}
              <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                <span style={{ fontSize: 11, fontFamily: 'var(--font-mono)', color: 'var(--accent)', border: '1px solid rgba(240,176,74,0.35)', borderRadius: 99, padding: '0 5px' }}>→</span>
                <span style={{ fontSize: 11, color: 'var(--fg-4)' }}>Tap → on a song to mark a segue</span>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* ── Right: Setlist document ──────────────────────────────────────────── */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>

        {/* Header fields */}
        <div className="glass" style={{ padding: '16px 18px', display: 'flex', flexDirection: 'column', gap: 12 }}>
          <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between' }}>
            <span className="t-eyebrow">Setlist details</span>
            {totalSongs > 0 && (
              <button
                onClick={clearSetlist}
                style={{ background: 'none', border: 0, cursor: 'pointer', fontSize: 11, color: 'var(--fg-4)', fontFamily: 'var(--font-sans)' }}
              >
                Clear all
              </button>
            )}
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 10 }}>
            {[
              { key: 'bandName' as const, placeholder: 'Band name', label: 'Band' },
              { key: 'date' as const, placeholder: 'Date', label: 'Date' },
              { key: 'venue' as const, placeholder: 'Venue / City', label: 'Venue' },
            ].map(({ key, placeholder, label }) => (
              <div key={key} style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
                <span style={{ fontSize: 10, color: 'var(--fg-4)', fontFamily: 'var(--font-mono)', textTransform: 'uppercase', letterSpacing: '0.12em' }}>{label}</span>
                <div className="glass faint" style={{ borderRadius: 'var(--r-sm)', padding: '6px 10px' }}>
                  <input
                    value={setlist[key]}
                    onChange={e => setSetlist(prev => ({ ...prev, [key]: e.target.value }))}
                    placeholder={placeholder}
                    style={{ background: 'transparent', border: 0, outline: 'none', color: 'var(--fg)', fontSize: 12.5, width: '100%' }}
                  />
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Setlist sections */}
        <div className="glass" style={{ padding: '8px 0', display: 'flex', flexDirection: 'column' }}>
          {([
            { setKey: 'set1' as SetKey, label: 'Set I', accentColor: 'var(--accent)' },
            { setKey: 'set2' as SetKey, label: 'Set II', accentColor: 'var(--accent-strong)' },
            { setKey: 'encore' as SetKey, label: 'Encore', accentColor: 'var(--fg-3)' },
          ]).map(({ setKey, label, accentColor }, sectionIdx) => (
            <React.Fragment key={setKey}>
              {sectionIdx > 0 && <div className="divider" style={{ margin: '6px 14px' }} />}
              <SetSection
                label={label}
                setKey={setKey}
                songs={setlist[setKey]}
                dragSource={dragSource}
                dropTarget={dropTarget}
                onDragOver={onDragOver}
                onDrop={onDrop}
                onDragLeave={onDragLeave}
                onDragStart={onDragStart}
                onDragEnd={onDragEnd}
                onToggleSegue={toggleSegue}
                onRemove={removeSong}
                accentColor={accentColor}
              />
            </React.Fragment>
          ))}

          {/* Grand total */}
          {grandTotal > 0 && (
            <>
              <div className="divider" style={{ margin: '8px 14px 4px' }} />
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '8px 14px 6px' }}>
                <span className="t-eyebrow">{totalSongs} song{totalSongs !== 1 ? 's' : ''} total</span>
                <span className="t-mono" style={{ fontSize: 11, color: 'var(--fg-3)' }}>Est. {fmtTotal(grandTotal)}</span>
              </div>
            </>
          )}
        </div>

        {/* Export button */}
        <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
          <button
            className="btn primary lg"
            disabled={totalSongs === 0 || exporting}
            onClick={handleExportPDF}
            style={{ flex: 1, justifyContent: 'center', opacity: totalSongs === 0 ? 0.5 : 1 }}
          >
            <Icon d={ICONS.download} size={14} />
            {exporting ? 'Opening print dialog…' : 'Export as PDF'}
          </button>
          {totalSongs === 0 && (
            <span className="t-small">Add songs to export</span>
          )}
        </div>

        {/* Duplicate warning — only after user has searched since last add */}
        {querySinceLastAdd && results.some(r => allTitles.has(r.title)) && (
          <div style={{
            padding: '10px 14px', borderRadius: 'var(--r-sm)',
            background: 'rgba(255,138,138,0.08)',
            border: '1px solid rgba(255,138,138,0.2)',
            fontSize: 12, color: 'var(--bad)',
          }}>
            Some songs in your results are already in the setlist. GD rarely repeated songs in a show.
          </div>
        )}
      </div>
    </div>
  )
}
