export const ERA_DEFS = [
  {
    id: 'primal',
    name: 'Primal Dead',
    years: '1965 – 1971',
    startYear: 1965,
    endYear: 1971,
    tag: 'Pigpen era',
    description: 'The raw, exploratory years anchored by Pigpen\'s blues-drenched vocals. Long psychedelic jams, R&B roots, and the first hints of the Dead\'s unique improvisational language.',
    sigSongs: ['Viola Lee Blues', 'Lovelight', 'Dark Star', 'St. Stephen'],
  },
  {
    id: 'europe72',
    name: "Europe '72",
    years: '1972 – 1974',
    startYear: 1972,
    endYear: 1974,
    tag: 'wall-of-sound',
    description: 'Peak improvisational power and the Wall of Sound PA system. New songwriting from Garcia/Hunter and Weir/Barlow, legendary European tours, and some of the longest Dark Stars ever played.',
    sigSongs: ['Dark Star', 'Playing in the Band', 'Eyes of the World', 'He\'s Gone'],
  },
  {
    id: 'hiatus',
    name: 'Hiatus & Return',
    years: '1975 – 1979',
    startYear: 1975,
    endYear: 1979,
    tag: 'studio era',
    description: 'A year-long hiatus in 1975 followed by a triumphant return. Keith and Donna Godchaux, Terrapin Station, and a more polished sound balanced against continued exploration.',
    sigSongs: ['Estimated Prophet', 'Terrapin Station', 'Fire on the Mountain', 'Shakedown Street'],
  },
  {
    id: 'brent',
    name: 'Brent Years',
    years: '1980 – 1990',
    startYear: 1980,
    endYear: 1990,
    tag: 'arena Dead',
    description: 'Brent Mydland\'s keyboards defined the sound of a decade. The Dead went arena-scale, expanded their catalog, and became one of the top-grossing touring acts in America.',
    sigSongs: ['Throwing Stones', 'Hell in a Bucket', 'Victim or the Crime', 'Dear Mr. Fantasy'],
  },
  {
    id: 'final',
    name: 'Final Tours',
    years: '1991 – 1995',
    startYear: 1991,
    endYear: 1995,
    tag: 'Vince & Bruce',
    description: 'Vince Welnick and Bruce Hornsby brought new colors. Late-career gems like Lazy River Road and Days Between sat alongside enduring classics, right up to the final show at Soldier Field.',
    sigSongs: ['Lazy River Road', 'Days Between', 'So Many Roads', 'Eternity'],
  },
]

export const ERA_IDS = ERA_DEFS.map(era => era.id)
